openapi: 3.2.0
info:
  title: Bamboo Exchange Rate API
  version: ''
  description: "The exchange rate section provides you with an endpoint that fetches real-time exchange rates effortlessly, enabling  accurate currency conversions and financial calculations. \n"
servers:
- url: https://powered-by-bamboo-sandbox.investbamboo.com
tags:
- name: Exchange Rate
  description: "The exchange rate section provides you with an endpoint that fetches real-time exchange rates effortlessly, enabling  accurate currency conversions and financial calculations. \n"
paths:
  /api/tenant/exchange_rate:
    get:
      tags:
      - Exchange Rate
      summary: Fetch Exchange Rate
      description: "Real-time exchange rate data enables accurate currency conversions for deposit, withdrawals and trade transactions.\n\nExchange rate data provides buy rates for converting USD to local currency when displaying prices, sell rates for converting local currency to USD when processing deposits, real-time updates with rates refreshed throughout the trading day, and support for multiple currencies including NGN, GHS, and ZAR.\n\n**Usage Guidelines:** \n- If deposit is being made in local currency, use the sell rate for deposits.\n- Use the Buy rate for Withdrawals if withdrawal is being converted back to local currency.\n- Apply consistent rates across user sessions for pricing consistency\n"
      operationId: Web.Api.Tenant.ExchangeRateController.exchange_rate
      parameters:
      - name: content-type
        in: header
        description: Acceptable content type
        example: application/json
        required: true
        schema:
          type: string
      - name: accept-language
        in: header
        description: Acceptable language; 'en' for English
        example: en
        required: true
        schema:
          type: string
      - name: x-client-token
        in: header
        description: API consumer token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRatesResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
components:
  schemas:
    ResourceNotFound:
      title: Resource not found
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: Resource not found (an incorrect url may have been used)
          example: Resource Not Found
      description: Error response for when the resource is not found within our data.
    ExchangeRatesResponse:
      title: Exchange rates response
      required:
      - exchange_rates
      type: object
      properties:
        exchange_rates:
          type: array
          description: list of exchange rates
          items:
            title: Exchange rate response
            required:
            - exchange_rate
            type: object
            properties:
              buy_rate:
                type: number
                description: Buy rate for requested currency
                example: 805
              currency:
                type: string
                description: The requested currency
                example: NGN
              currency_symbol:
                type: number
                description: Symbol of requested currency
                example: ₦
              flag_image:
                type: string
                description: Flag_image
              id:
                type: number
                description: ID for requested currency
                example: 2
              residence_country:
                type: string
                description: Country for requested currency
                example: NGA
              sell_rate:
                type: number
                description: Buy rate for requested currency
                example: 868
x-logo:
  url: bamboo-logo.png
  altText: bamboo logo
x-tagGroups:
- name: Authentication
  tags:
  - Authentication
  - Account Management
- name: Money Movement
  tags:
  - Overview
  - Deposits
  - Withdrawals
- name: US Brokerage Services
  tags:
  - Portfolio Reporting
  - US Securities
  - US Stock Trading
  - US Stock Events
- name: Utilities
  tags:
  - Dictionaries
  - Market Activity
  - Exchange Rate
  - Featured Themes
  - Financial Documents
